# Site settings
title: ChrisTekh
header-img: img/home-bg.jpg
email: nwambachristian@gmail.com
description: "Simply programming"
baseurl: ""
url: "http://christekh.com"
twitter_username: chrizt_n
github_username:  christiannwamba
facebook_username:  nwambachristian

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
